baseurl = "http://docs.gigaspaces.com/"
languageCode = "en-us"
title = "XAP Documentation"
theme="hugo-bootswatch"
uglyurls=true

[params]
    latest_xap_release= "10.2"
    latest_java_url= "/xap102"
    latest_net_url= "/xap102net"
    latest_adm_url= "/xap102adm"
    latest_sec_url= "/xap102sec"
    latest_net_tut_url= "/xap102nettut"
    latest_java_tut_url= "/xap102tut"




[[menu.footer]]
    name = "Blog"
    url = "/posts"

[[menu.xap101]]
    name = "Blog"
    url = "/xap110"

[params.xap97]
    maven-version=            "9.7.0-10496-RELEASE"
    gshome-directory=         "gigaspaces-xap-premium-9.7.0-ga"
    default-lookup-group=     "gigaspaces-9.7.0-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-9.7.0-ga-b10496.zip"
    xap-version=              "9.7.0"
    xap-release=              "9.7"
    msi-filename=             "GigaSpaces-XAP.NET-Premium-9.7.0.10496-GA-x86.msi"
    gshome-net-directory=     "XAP.NET 9.7.0 x86"

[params.xap100]
    java-version=             "7"

    spring=                   "3.2"
    mongo-java-driver=        "2.11.2"
    antlr4-runtime=           "4.0"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"

# Path and versions
    maven-version=            "10.0.1-11800-RELEASE"
    gshome-directory=         "gigaspaces-xap-premium-10.0.1-ga"
    default-lookup-group=     "gigaspaces-10.0.1-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-10.0.1-ga-b11800.zip"
    xap-version=              "10.0"
    xap-release=              "10.0.1"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-10.0.1.11800-GA-x86.msi"
    gshome-net-directory=      "XAP.NET 10.0.1 x86"

[params.xap101]
# 10.1 Definitions
    java-version=             "7"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "2.11.2"
    antlr4-runtime=           "4.0"
    mule=                     "3.5"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"

# Path and versions
    maven-version=            "10.1.1-b-12800-RELEASE"
    gshome-directory=         "gigaspaces-xap-premium-10.1.1-ga"
    default-lookup-group=     "gigaspaces-10.1.1-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-10.1.1-ga-b12800.zip"
    xap-version=              "10.1"
    xap-release=              "10.1.1"
    blobstore=                "blobstore-10.1.1-11800_RELEASE_1.noarch"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-10.1.1.12600-GA-x86.msi"
    gshome-net-directory=      "XAP.NET 10.1.1 x86"


[params.xap102]
# 10.2 Definitions
    java-version=             "8"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "2.11.2"
    antlr4-runtime=           "4.0"
    mule=                     "3.5"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"

# Path and versions
    maven-version=            "10.2.0-13800-RELEASE"
    blobstore=                "blobstore-10.2.0-13800_RELEASE.noarch"
    gshome-directory=         "gigaspaces-xap-premium-10.2.0"
    default-lookup-group=     "gigaspaces-10.2.0-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-10.2.0-ga-b13800.zip"
    xap-version=              "10.2"
    xap-release=              "10.2.0"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-10.2.0.m-13800-x86.msi"
    gshome-net-directory=      "XAP.NET 10.2.0 x86"



[params.xap110]
# 10.2 Definitions
    java-version=             "8"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "2.11.2"
    antlr4-runtime=           "4.0"
    mule=                     "3.5"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"

# Path and versions
    maven-version=            "11.0.0-13800-RELEASE"
    blobstore=                "blobstore-11.0.0-13800_RELEASE.noarch"
    gshome-directory=         "gigaspaces-xap-premium-11.0.0"
    default-lookup-group=     "gigaspaces-11.0.0-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-11.1.0-ga-b13800.zip"
    xap-version=              "11.0"
    xap-release=              "11.0.0"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-11.0.0.m-13800-x86.msi"
    gshome-net-directory=      "XAP.NET 11.0.0 x86"







  