version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers #circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
      - checkout
      - run: 
          name: Version check
          command: |
            java -version
            mvn -version
            python --version
      - run:
          name: Install AWS CLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            aws --version
      - run: 
          name: Install Hugo
          command: ./install-hugo.sh
      - run: 
          name: Build docs using Hugo
          command: ./build-site.sh
      - run: echo branch [$CIRCLE_BRANCH] tag [$CIRCLE_TAG]
      - run: 
          name: Publish output
          command: |
            if [ -n "$CIRCLE_TAG" ]
            then
              echo "Publishing to production..."
              export DOCS_TARGET=PROD 
            else
              echo "Adding staging files..."
              cp staging/* _site
              echo "Publishing to staging..."
              export DOCS_TARGET=STAGING
            fi
            s3_website push
workflows:
  version: 2
  staging:
    jobs:
      - build:
          filters:
            branches:
              only: master
  production:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-.*/
