baseurl = "http://docs.gigaspaces.com/"
languageCode = "en-us"
title = "XAP Documentation"
theme="hugo-bootswatch"
uglyurls=true



[blackfriday]
# https://github.com/spf13/hugo/blob/master/docs/content/overview/configuration.md#configure-blackfriday-rendering
plainIdAnchors=true

[params]
    latest_xap_release= "12.3"
    latest_java_url= "/xap/12.3/dev-java"
    latest_net_url= "/xap/12.3/dev-dotnet"
    latest_adm_url= "/xap/12.3/admin"
    latest_sec_url= "/xap/12.3/security"
    latest_net_tut_url= "/xap/12.3/dev-dotnet/xapnet-basics.html"
    latest_java_tut_url= "/xap/12.32/started/xap-basics.html"
    latest_started_url= "/xap/12.3/started"
    latest_overview_url= "/xap/12.3/overview"
    latest_xap_url= "/xap/12.3/"
    latest_api_java_url= "https://docs.gigaspaces.com/api/xap/12.3.0/java"
    latest_api_dotnet_url= "https://docs.gigaspaces.com/api/xap/12.3.0/dotnet/html"




[[menu.footer]]
    name = "Blog"
    url = "/posts"

[[menu.xap101]]
    name = "Blog"
    url = "/xap110"

[params.xap97]
    maven-version=            "9.7.0-10496-RELEASE"
    gshome-directory=         "gigaspaces-xap-premium-9.7.0-ga"
    default-lookup-group=     "gigaspaces-9.7.0-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-9.7.0-ga-b10496.zip"
    xap-version=              "9.7.0"
    xap-release=              "9.7"
    msi-filename=             "GigaSpaces-XAP.NET-Premium-9.7.0.10496-GA-x86.msi"
    gshome-net-directory=     "XAP.NET 9.7.0 x86"

[params.xap100]
    java-version=             "7"

    spring=                   "3.2"
    mongo-java-driver=        "2.11.2"
    antlr4-runtime=           "4.0"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"

# Path and versions
    maven-version=            "10.0.1-11800-RELEASE"
    gshome-directory=         "gigaspaces-xap-premium-10.0.1-ga"
    default-lookup-group=     "gigaspaces-10.0.1-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-10.0.1-ga-b11800.zip"
    xap-version=              "10.0"
    xap-release=              "10.0.1"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-10.0.1.11800-GA-x86.msi"
    gshome-net-directory=      "XAP.NET 10.0.1 x86"

[params.xap101]
# 10.1 Definitions
    java-version=             "7"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "2.11.2"
    antlr4-runtime=           "4.0"
    mule=                     "3.5"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"

# Path and versions
    maven-version=            "10.1.1-b-12800-RELEASE"
    gshome-directory=         "gigaspaces-xap-premium-10.1.1-ga"
    default-lookup-group=     "gigaspaces-10.1.1-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-10.1.1-ga-b12800.zip"
    xap-version=              "10.1"
    xap-release=              "10.1.1"
    blobstore=                "blobstore-10.1.1-11800_RELEASE_1.noarch"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-10.1.1.12600-GA-x86.msi"
    gshome-net-directory=      "XAP.NET 10.1.1 x86"


[params.xap102]
# 10.2 Definitions
    java-version=             "8"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "2.11.2"
    antlr4-runtime=           "4.0"
    mule=                     "3.5"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"

# Path and versions
    maven-version=            "10.2.0-13800-RELEASE"
    blobstore=                "blobstore-10.2.0-13800_RELEASE.noarch"
    gshome-directory=         "gigaspaces-xap-premium-10.2.0"
    default-lookup-group=     "gigaspaces-10.2.0-XAPPremium-ga"
    build-filename=           "gigaspaces-xap-premium-10.2.0-ga-b13800.zip"
    xap-version=              "10.2"
    xap-release=              "10.2.0"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-10.2.0.m-13800-x86.msi"
    gshome-net-directory=      "XAP.NET 10.2.0 x86"



[params.xap110]
# 11.0 Definitions
    java-version=             "8"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "3.2.0"
    antlr4-runtime=           "4.0"
    mule=                     "3.7.0"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"
    rocksdb=                  "4.1.0"

# Path and versions
    maven-version=            "11.0.0-14800-RELEASE"
    spatial=                  "11.0.0-14800-RELEASE"
#    blobstore=                "blobstore-11.0.0-13800_RELEASE.noarch"
    gshome-directory=         "gigaspaces-xap-premium-11.0.0-ga"
    default-lookup-group=     "xap-11.0.0"
    build-filename=           "gigaspaces-xap-premium-11.0.0-ga-b14800.zip"
    xap-version=              "11.0"
    xap-release=              "11.0.0"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-11.0.0.m-14800-x86.msi"
    gshome-net-directory=      "XAP.NET 11.0.0 x86"

[params.xap120]
# 12.0 Definitions
    java-version=             "8"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "3.2.0"
    antlr4-runtime=           "4.0"
    mule=                     "3.7.0"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"
    rocksdb=                  "4.1.0"
    hsql=                     "2.3.2"
    topthreads=               "1.0.0"
    scala=                    "2.11.6"

# Path and versions
    maven-version           = "12.0.1"
    gshome-directory        = "gigaspaces-xap-premium-12.0.0-ga-b16000"
    gshome-directory-oss    = "gigaspaces-xap-open-12.0.1-ga-b16600"
    default-lookup-group    = "xap-12.0.0"
    build-filename          = "gigaspaces-xap-premium-12.0.0-ga-b16000.zip"
    build-filename-oss      = "gigaspaces-xap-open-12.0.1-ga-b16600.zip"
    xap-version             = "12.0"
    xap-release             = "12.0.1"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-12.0.1-x86.msi"
    gshome-net-directory=      "XAP.NET 12.0.1 x86"

# gigaspaces-xap-open-12.0.1-ga-b16600


[params.xap121]
# 12.1 Definitions
    java-version=             "8"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "3.2.0"
    antlr4-runtime=           "4.0"
    mule=                     "3.7.0"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"
    rocksdb=                  "4.1.0"
    hsql=                     "2.3.2"
    topthreads=               "1.0.0"
    scala=                    "2.11.6"

# Path and versions
    maven-version           = "12.1.1"
    gshome-directory        = "gigaspaces-xap-premium-12.1.1-ga-b17100"
    gshome-directory-oss    = "gigaspaces-xap-open-12.1.1-ga-b17100."
    default-lookup-group    = "xap-12.1.0"
    build-filename          = "gigaspaces-xap-premium-12.1.1-ga-b17100.zip"
    build-filename-oss      = "gigaspaces-xap-open-12.1.1-ga-b17100.zip"
    xap-version             = "12.1.1"
    xap-release             = "12.1.1"

# DOT NET
    msi-filename=              "GigaSpaces-XAP.NET-Premium-12.1.1-x86.msi"
    gshome-net-directory=      "XAP.NET 12.1.1 x86"


[params.xap122]
# 12.2 Definitions
    java-version=             "8"
    scala-version=            "2.11.8"
    spark-version=            "2.2.0"

# 12.2 Path and versions
    maven-version           = "12.2.1"
    gshome-directory        = "gigaspaces-xap-12.2.1-ga-b18100"
    gshome-directory-oss    = "gigaspaces-xap-open-12.2.1-ga-b18100"
    default-lookup-group    = "xap-12.2.1"
    build-filename          = "gigaspaces-xap-12.2.1-ga-b18100.zip"
    build-filename-oss      = "gigaspaces-xap-open-12.2.1-ga-b18100.zip"
    xap-version             = "12.2.1"
    xap-release             = "12.2.1"

# 12.2 DOT NET
    msi-filename=              "gigaspaces-xap.net-12.2.1-ga-b18100.msi"
    gshome-net-directory=      "XAP.NET-12.2.1-x64"

# Jar versions
    spring=                   "4.1"
    mongo-java-driver=        "3.2.0"
    antlr4-runtime=           "4.0"
    mule=                     "3.7.0"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"
    rocksdb=                  "5.5.1"
    hsql=                     "2.3.2"
    topthreads=               "1.0.0"
    scala=                    "2.11.6"
    xap-sql_path=             "./xap-calcite/target/gigaspaces-xap-jdbc-1.12.0-SNAPSHOT.jar"

[params.xap123]
# 12.3 Definitions
    java-version=             "8"
    scala-version=            "2.11.8"
    spark-version=            "2.3.1"

# 12.3 Path and versions
    maven-version           = "12.3.1"
    gshome-directory        = "gigaspaces-xap-enterprise-12.3.1-ga-b19300"
    gshome-directory-oss    = "gigaspaces-xap-12.3.1-ga-b19300"
    default-lookup-group    = "xap-12.3.1"
    build-filename          = "gigaspaces-xap-enterprise-12.3.1-ga-b19300.zip"
    build-filename-oss      = "gigaspaces-xap-12.3.1-ga-b19300.zip"
    xap-version             = "12.3"
    xap-release             = "12.3"
	rest-version			= "v2"

# 12.3 DOT NET
    msi-filename=              "gigaspaces-xap.net-12.3.1-ga-b19300.msi"
    gshome-net-directory=      "XAP.NET-12.3.1-x64"

# Jar versions
    spring=                   "4.3"
    mongo-java-driver=        "3.2.0"
    antlr4-runtime=           "4.0"
    mule=                     "3.7.0"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"
    rocksdb=                  "5.11.3"
    hsql=                     "2.3.2"
    topthreads=               "1.0.0"
    scala=                    "2.11.6"
    xap-sql_path=             "./xap-calcite/target/gigaspaces-xap-jdbc-1.12.0-SNAPSHOT.jar"

[params.xap140]
# 14.0 Definitions
    java-version=             "8"
    scala-version=            "2.11.8"
    spark-version=            "2.3.2"

# 14.0 Path and versions
    maven-version           = "14.0.0"
    gshome-directory        = "gigaspaces-xap-enterprise-14.0.0-rc1-b19915"
    gshome-directory-oss    = "gigaspaces-xap-14.0.0-rc1-b19915"
    default-lookup-group    = "xap-14.0.0"
    build-filename          = "gigaspaces-xap-enterprise-14.0.0-rc1-b19915.zip"
    build-filename-oss      = "gigaspaces-xap-14.0.0-rc1-b19915.zip"
    xap-version             = "14.0"
    xap-release             = "14.0"
	rest-version			= "v2"

# 14.0 DOT NET
    msi-filename=              "gigaspaces-xap.net-14.0.0-rc1-b19915.msi"
    gshome-net-directory=      "XAP.NET-14.0.0-x64"

# Jar versions
    spring=                   "4.3"
    mongo-java-driver=        "3.2.0"
    antlr4-runtime=           "4.0"
    mule=                     "3.7.0"
    mongo-datasource=         "10.0.0-SNAPSHOT"
    openjpa=                  "2.0.1"
    cassandra-clientutil=     "1.1.6"
    cassandra-thrift=         "1.1.6"
    cassandra-jdbc=           "1.1.2"
    hector-core=              "1.1-2"
    slf4j-api=                "1.6.6"
    slf4j-jdk14=              "1.6.6"
    rocksdb=                  "5.11.3"
    hsql=                     "2.3.2"
    topthreads=               "1.0.0"
    scala=                    "2.11.6"
    xap-sql_path=             "./xap-calcite/target/gigaspaces-xap-jdbc-1.12.0-SNAPSHOT.jar"

